# fly.toml app configuration file generated for test-xs7w8a on 2026-02-19T06:52:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'test-xs7w8a'
primary_region = 'iad'

[build]


[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
